spring:
  application:
    name: service2

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://host.docker.internal:8761/eureka/
  instance:
    prefer-ip-address: true